[GLOBAL]
pants_version = "2.23.1"
backend_packages.add = [
  "pants.backend.build_files.fmt.black",  
  "pants.backend.python",
  "pants.backend.python.lint.docformatter",
  "pants.backend.python.lint.black",
  "pants.backend.python.lint.flake8",
  "pants.backend.python.lint.isort",
  "pants.backend.python.typecheck.mypy",
]

[source]
root_patterns = ["/src", "/tests"]

[python]
interpreter_constraints = ["==3.9.*"]
enable_resolves = true
resolves = { python-default = "python-default.lock"}

[python-bootstrap]
# This searches the Python interpreters in your machine. Installation of pyenv is highly encouraged
# Make sure that at least one Python interpreter is in PATH
search_path = ["<PATH>", "<PYENV>"]